---
title: "ST558ProgrammingHW3"
author: "Holly Probasco"
format: pdf
editor: visual
---

## Task 1

### part a

Here we don't use read_csv specifically because the delimiter is not a comma.

```{r}
library(tidyverse)
data = read_csv2('data/data.txt') 
data
```

### part b

```{r}
data2 = read_delim('data/data2.txt', delim = "6", col_names = TRUE, 
col_types = c("f","d","c"))
data2
```

## Task 2

### part a

```{r}
trailblazer <- read_csv("data/trailblazer.csv")
head(trailblazer)
```

### part b

```{r}
trailblazer_longer = trailblazer |> pivot_longer(cols = 2:11, 
names_to = c('Game', 'Location'), names_sep = "_", 
values_to = 'Points')
head(trailblazer_longer, n=5)
```

### part c

```{r}
trailblazer_wider = trailblazer_longer |> 
pivot_wider(names_from = Location, values_from = Points) |> 
  group_by(Player) |>  
mutate(mean_home = mean(Home, na.rm=TRUE), mean_away = mean(Away, na.rm = TRUE),
pt_diff = sum(Home,na.rm=TRUE)-sum(Away,na.rm=TRUE)) |> 
  arrange(desc(pt_diff))
```

The players that scored more at home than away are Jusuf Nurkic (55 more), Robert Covington (45 more), and Damian Lillard (41 more)

## Task 3

### part a

```{r}
library(palmerpenguins)
```

-   <NULL> means that there is no data there

-   \<dbl \[52\]\> means this element is a double list of size 52

-   \<list\> means that this is a column of lists

### part b
```{r}
penguins |>  summarise(n = n(), .by = c(species, island)) |> 
  pivot_wider(names_from = island, values_from = n, values_fill = 0)
```

## Task 4
```{r}
penguins |> mutate(bill_length_mm = case_when(is.na(bill_length_mm) 
   & species == "Adelie" ~ 26, is.na(bill_length_mm) & species ==
  "Gentoo" ~ 30, TRUE ~ bill_length_mm)) |> 
  arrange(bill_length_mm) |> head(penguins, n=10)
```

